version: 2.1

commands:
  gotest:
    description: Run Golang tests using gotestsum
    parameters:
      version:
        type: string
        default: "go110"
    steps:
      - run: mkdir -p /tmp/test-results

      - run: gotestsum --junitfile /tmp/test-results/<< parameters.version >>-unit-tests.xml -- -timeout 5m -p 1 ./...

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

jobs:
  go110:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/customerio/go-customerio
    steps:
      - checkout
      - gotest:
          version: "go110"
  go111:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/customerio/go-customerio
    steps:
      - checkout
      - gotest:
          version: "go111"
  go112:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/customerio/go-customerio
    steps:
      - checkout
      - gotest:
          version: "go112"

workflows:
  version: 2
  test:
    jobs:
    - go110:
        context: cio-integration
    - go111:
        context: cio-integration
    - go112:
        context: cio-integration